"""id's removed

Revision ID: e88f1290fc9b
Revises: d90619132a09
Create Date: 2025-02-13 12:12:11.598084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88f1290fc9b'
down_revision: Union[str, None] = 'd90619132a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_index('ix_subscribers_id', table_name='subscribers')
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.create_index('ix_subscribers_id', 'subscribers', ['id'], unique=False)
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
